language: node_js
sudo: required
cache:
  directories:
    - node_modules
    - bower_components
node_js:
  - 5.4.0
before_install:
  - npm install -g grunt-cli
install:
  - npm install
before_script:
  - npm install -g bower
  - bower install --force
script:
  - grunt build
addons:
  sauce_connect:
    username: masterspambot
  jwt:
    secure: o0AuB2xpLrNaTyg26Xi6g81ZyE3dVvsNA18sHLAmkmdtVI0t88CH6W5lAXO/+NO5cieR2x8qvRY6tYpeC03o2OC3AeSzuL6CC4Sy27RS9KArdJfmJgirVv/3JuxjSMyqyXTUonDmEuZcwX7CNmTXG3fOnGbTuofj0st1mezSTwk=
deploy:
  provider: npm
  email: blazej.krysiak@gmail.com
  api_key:
    secure: XF7TJRCaz5+otwBHl07ppHsWBYpwJ6sEw4PxzAvkljBcqsZv826nOECQjNaFT0CtfnwwpQ+rZhpl1sdB9BhndmbGgkjyXNGAa1rLzDnWGruh7FR80mpZ43LmEDNzgQcJqS70hj2uWcosRnveVhkllsVK3uf6gKTsl4TnBGWYPaU=
  on:
    tags: true
    repo: Narzerus/angular-permission
    branch: master
